# Generated by Django 3.2.24 on 2024-03-05 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('initial_balance', models.DecimalField(decimal_places=4, max_digits=19)),
                ('lots', models.IntegerField()),
                ('equity_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inverse', models.BooleanField(default=False)),
                ('pyramid', models.BooleanField(default=False)),
                ('market_data_source', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('open_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('leverage', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('pnl', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('pnl_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(max_length=10)),
                ('strategy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trading.strategy')),
            ],
        ),
    ]
