# Generated by Django 3.2.24 on 2024-02-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy_id', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=10)),
                ('initial_balance', models.FloatField()),
                ('lots', models.IntegerField()),
                ('equity_percent', models.FloatField()),
                ('inverse', models.BooleanField(default=False)),
                ('pyramid', models.BooleanField(default=False)),
                ('market_data_source', models.CharField(max_length=255)),
                ('open_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('close_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True)),
                ('entry_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('exit_time', models.DateTimeField(blank=True, default=None, null=True)),
                ('pnl', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, verbose_name='Profit and Loss (USD)')),
            ],
        ),
    ]
