# Generated by Django 3.2.24 on 2024-02-29 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='strategy',
            name='action',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
