# Generated by Django 3.2.24 on 2024-02-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0003_alter_strategy_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='lots',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
