# Generated by Django 3.2.24 on 2024-02-29 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading', '0004_alter_strategy_lots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='strategy',
            name='equity_percent',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
